# Generated by Django 3.2.7 on 2021-09-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre')),
                ('mobile_phone', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre')),
                ('mobile_phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.client')),
                ('number_of_people', models.IntegerField(blank=True, default=0, null=True, verbose_name='Numero de personas')),
                ('table', models.IntegerField(blank=True, default=0, null=True, verbose_name='Mesa')),
                ('reservation_time', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora reserva')),
                ('state', models.CharField(choices=[('Confirmada', 'Confirmada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], default='agua', max_length=100, verbose_name='Estado')),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.business')),
            ],
        ),
    ]
